spring:
  application:
    name: spring-demo

  mail:
    host: smtp.gmail.com
    port: 587
    username: vutranit04@gmail.com
    password: dwfacvtomlhfllcb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com

  datasource:
    url: jdbc:mysql://localhost:3306/spring_demo?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

server:
  port: 8080

# JWT Configuration
app:
  jwt:
    secret: MySecretKeyForJWTTokenGenerationThatIsAtLeast256BitsLongForHS256Algorithm2026
    expiration: 86400000  # 24 hours in milliseconds
